### ISSUE TITLE
Enhacement rather than issue!

### ISSUE THREAD

**Issue by Commitosaurus** [Kelo/Google-Sheets-to-Discord#4] opened 2022-09-19 12:31 UTC
This script is great thank you. The spreadsheet that I'm using it on will be routinley populated with a new row where I'd like to call out just the values in Column2 (ColB) and Column28 (ColAB). I wondering if there is a way to tweak this line and the associated variables to display just these values on the Discord notification?

"value": "Name: "+ **ColB** +"\nGrand Total: " + **ColAB** + "\nEdit made: "+ reason,

Many thanks in advance!

**Comment by Kelo** [comment] 2022-09-19 14:37
You could do something like this:
```
var rangeNotation = event.range.getA1Notation();
var rowNumber =  rangeNotation.substring(1,2);

var colB = event.range.getSheet().getRange("B"+rowNumber).getValue();
var colAB = event.range.getSheet().getRange("AB"+rowNumber).getValue();
```

**Comment by Commitosaurus** [comment] 2022-09-19 22:14
Incredible thank you Kelo! Worked perfectly. Very much appreciated!
By any chance have you had much experience with triggering this when the spreadsheet is being updated with an API rather than onEdit would onChange work?
The spreadsheet currently updates form a jot form and I’m looking for this to trigger the discord message when the jot form updates the Google sheet if that makes sense. Any guidance on this again is hugely appreciated!

**Comment by Kelo** [comment] 2022-09-20 07:41
I'm not sure, I'd probably say it's easier to setup the discord webhook on jot form.

**Comment by Kelo** [comment] 2022-09-20 10:26
Have you checked to see if `e.changeType` ever returns "other"?
If it doesn't equal "other" then it won't add any items.

If it is returning other sometimes, then I'd recommend using an else statement to handle responses for different `e.changeType` 's

E.g. 
```
if (e.changeType == "OTHER") {

  var sheet_name = event.range.getSheet().getName();
  var rangeNotation = event.range.getA1Notation();
  var oldValue = event.oldValue;
  var value = event.value;
  var rangeNotation = event.range.getA1Notation();
  var rowNumber =  rangeNotation.substring(1,2);

  var colB = event.range.getSheet().getRange("B"+rowNumber).getValue();
  var colAB = event.range.getSheet().getRange("AB"+rowNumber).getValue();
  var colAN = event.range.getSheet().getRange("AN"+rowNumber).getValue();
}

var items = [];

// If you only want to watch a certain column
var column_id = 2
// If not the column you want to watch
if (column_id < e.range.getColumn() || column_id > e.range.getLastColumn() ){
    // Do nothing
    return;
}

if (value == undefined && oldValue == undefined){
  if (rangeNotation.includes(':')){
    reason = "Multiple Cells edited";
  }
  else{
    reason = "Cell value deleted";
  }
}
else{
  if (oldValue == undefined){
    oldValue = "Empty cell";
  }

  if (value == undefined){
      value = "Empty cell";
  }
  reason = oldValue + " -> " + value
}

if (e.changeType == "OTHER"){
  items.push({
      "name": "An Entry has been added to the Sales Log via OTHER",
      "value": "SUBTEXT: "+ colB +"\nSUBTEXT: " + colAB + "\nSUBTEXT: "+ colAN,
      "inline": false
  });
} else {
  items.push({
      "name": "An Entry has been added to the Sales Log",
      "value": "SUBTEXT: "+ reason,
      "inline": false
  });
```

Not sure if that's the exact type of functionality you wanted, but you should get the gist of what you would need to do.

**Comment by Kelo** [comment] 2022-09-20 11:12
Maybe a better question for me to ask is what are you trying to accomplish with the changetype?
What are the outcomes and when would those outcomes occur?

**Comment by SgtGino** [comment] 2022-09-20 11:20
I was following this thread to see if I could get the script to trigger when the Google sheet is updated when my Jot Form is submitted when I came accross the changeType.

https://stackoverflow.com/questions/16183127/trigger-google-apps-script-when-jotform-submitted-and-integrated-to-spreadsheet

After a bit of trial and error with my limited knowledge the code I shared above is working when the Jot Form is updated now which is exactly what I want it to do however it would be the icing on the cake if I'm able to inlclude the results from colB, colAB and colAN as part of the sub text in my second screenshot if that makes sense? 
Apologies if I'm not being too clear and I do ery much apprecite your guidance here.

**Comment by Kelo** [comment] 2022-09-20 11:29
Ahhhhh I see!

I didn't notice you changed `function onEdit(event)` to `function onChange(e)` 

So since you changed the function parameter from `event` to `e` you need to replace every usage of `event` to `e` in the code aswell!

For example:
```
var sheet_name = event.range.getSheet().getName();
var rangeNotation = event.range.getA1Notation();
var oldValue = event.oldValue;
var value = event.value;
var rangeNotation = event.range.getA1Notation();
var rowNumber =  rangeNotation.substring(1,2);

var colB = event.range.getSheet().getRange("B"+rowNumber).getValue();
var colAB = event.range.getSheet().getRange("AB"+rowNumber).getValue();
var colAN = event.range.getSheet().getRange("AN"+rowNumber).getValue();
```

Would change to:
```
var sheet_name = e.range.getSheet().getName();
var rangeNotation = e.range.getA1Notation();
var oldValue = e.oldValue;
var value = e.value;
var rangeNotation = e.range.getA1Notation();
var rowNumber =  rangeNotation.substring(1,2);

var colB = e.range.getSheet().getRange("B"+rowNumber).getValue();
var colAB = e.range.getSheet().getRange("AB"+rowNumber).getValue();
var colAN = e.range.getSheet().getRange("AN"+rowNumber).getValue();
```

**Comment by SgtGino** [comment] 2022-09-20 11:38
Ahh yeah sorry I didn't make that clear earlier my bad... I did try that however earlier whislt doing my best trail and error approach and it still seems to just show whats in the ``` var options``` and seemingly ignores the ```items.push``` above!

![image](https://user-images.githubusercontent.com/109251153/191247579-24bf8744-60c6-4326-af35-cb312155ee98.png)

var POST_URL = "MY DISCORD WEBHOOK URL"

var randomColor = Math.floor(Math.random()*16777215);

function onChange(e){

if (e.changeType == "OTHER") {

  var sheet_name = e.range.getSheet().getName();
  var rangeNotation = e.range.getA1Notation();
  var oldValue = e.oldValue;
  var value = e.value;
  var rangeNotation = e.range.getA1Notation();
  var rowNumber =  rangeNotation.substring(1,2);

var colB = e.range.getSheet().getRange("B"+rowNumber).getValue();
var colAB = e.range.getSheet().getRange("AB"+rowNumber).getValue();
var colAN = e.range.getSheet().getRange("AN"+rowNumber).getValue();

  var items = [];

  // If you only want to watch a certain column
  var column_id = 2
  // If not the column you want to watch
  if (column_id < e.range.getColumn() || column_id > e.range.getLastColumn() ){
      // Do nothing
      return;
  }

  if (value == undefined && oldValue == undefined){
    if (rangeNotation.includes(':')){
      reason = "Multiple Cells edited";
    }
    else{
      reason = "Cell value deleted";
    }
  }
  else{
    if (oldValue == undefined){
      oldValue = "Empty cell";
    }

    if (value == undefined){
        value = "Empty cell";
    }
    reason = oldValue + " -> " + value
  }
  
  items.push({
      "name": "An Entry has been added to the Sales Log",
      "value": "Lead Mech: "+ colB +"\nAmount: " + colAB + "\nMats Used: "+ colAN,
      "inline": false
  });
**}**
  var options = {
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
        },
        "payload": JSON.stringify({
            "content": "‌",
            "embeds": [{
                "title": "JOB COMPLETE",
                "color": randomColor,
                "fields": items,
                "timestamp": new Date().toISOString()
            }]
        })
    };
    UrlFetchApp.fetch(POST_URL, options);
}

If I move the closing brace for the ```changeType```, or try to add the else statements into the script, the notifcation stops sending all together for some reason!

**Comment by Kelo** [comment] 2022-09-20 11:45
Can you try edit the title of the embed so the line looks like:
`"title": ""+e.changeType,`

then run it and show me the embed :)

I'm thinking that the issue is that changeType isn't OTHER.

**Comment by SgtGino** [comment] 2022-09-20 11:48
Gotcha, it chnaged the title to;

![image](https://user-images.githubusercontent.com/109251153/191249679-2f5e750e-9c5b-443f-ae51-0835fc9e30b1.png)

Shall I change the ```changeType``` to EDIT!?

**Comment by Kelo** [comment] 2022-09-20 11:56
Yup :)

**Comment by SgtGino** [comment] 2022-09-20 11:57
Tired to swap out ```OTHER``` to ```EDIT``` but it stops sending the notification :/

**Comment by Kelo** [comment] 2022-09-20 11:58
Change it back and put `var items = [];` above `if (e.changeType == "OTHER") {`

**Comment by SgtGino** [comment] 2022-09-20 12:03
Still just the title and timestamp at the mo!

![image](https://user-images.githubusercontent.com/109251153/191252423-84cd5ecb-d534-45fd-99f0-9b3132834842.png)

var POST_URL = "MY DISCORD URL"

var randomColor = Math.floor(Math.random()*16777215);

function onChange(e){

var items = [];

if (e.changeType == "OTHER") {

  var sheet_name = e.range.getSheet().getName();
  var rangeNotation = e.range.getA1Notation();
  var oldValue = e.oldValue;
  var value = e.value;
  var rangeNotation = e.range.getA1Notation();
  var rowNumber =  rangeNotation.substring(1,2);

var colB = e.range.getSheet().getRange("B"+rowNumber).getValue();
var colAB = e.range.getSheet().getRange("AB"+rowNumber).getValue();
var colAN = e.range.getSheet().getRange("AN"+rowNumber).getValue();

  // If you only want to watch a certain column
  var column_id = 2
  // If not the column you want to watch
  if (column_id < e.range.getColumn() || column_id > e.range.getLastColumn() ){
      // Do nothing
      return;
  }

  if (value == undefined && oldValue == undefined){
    if (rangeNotation.includes(':')){
      reason = "Multiple Cells edited";
    }
    else{
      reason = "Cell value deleted";
    }
  }
  else{
    if (oldValue == undefined){
      oldValue = "Empty cell";
    }

    if (value == undefined){
        value = "Empty cell";
    }
    reason = oldValue + " -> " + value
  }
  
  items.push({
      "name": "An Entry has been added to the Sales Log",
      "value": "Lead Mech: "+ colB +"\nAmount: " + colAB + "\nMats Used: "+ colAN,
      "inline": false
  });
}
  var options = {
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
        },
        "payload": JSON.stringify({
            "content": "‌",
            "embeds": [{
                "title": ""+e.changeType,
                "color": randomColor,
                "fields": items,
                "timestamp": new Date().toISOString()
            }]
        })
    };
    UrlFetchApp.fetch(POST_URL, options);
}

**Comment by Kelo** [comment] 2022-09-20 12:05
And when you change `if (e.changeType == "OTHER") {` to `if (e.changeType == "EDIT") {` it fails?

What happens when you remove the if statement?

**Comment by SgtGino** [comment] 2022-09-20 12:14
Thats right yeah, although I've just noticed when I remove the content I put in the cell an embed called FORMAT triggers;

![image](https://user-images.githubusercontent.com/109251153/191253808-fd40157c-85ce-42ed-9d22-e501e58005b2.png)

I can see the Trigger executed for the Format, but this is what the fail shows on the execution log if that helps. 

![image](https://user-images.githubusercontent.com/109251153/191254796-fb69e5e9-a31f-4408-b9f6-30acb4c4318f.png)

I'll try removing the if statement now but I think it stops the trigger off memory from trying earlier

**Comment by SgtGino** [comment] 2022-09-20 12:18
Yeah removing the if statement stops the notification with the same error as pictured above. Really do appreciate you sticking with me to try find a resolution here!

**Comment by SgtGino** [comment] 2022-09-20 12:19
Is there a way to maybe look up the variables and add them to the embed as part of the ```var options``` section!?

**Comment by SgtGino** [comment] 2022-09-20 12:26
```if (e.changeType == "edit"``` Sends the notification but as soon as its capitalised it stops

**Comment by Kelo** [comment] 2022-09-20 12:27
so "edit" works as intended? Or is there still an issue

**Comment by SgtGino** [comment] 2022-09-20 12:31
Sorry yes there is still and issue as changing to lowercase does send the notifications again but it doesn't include the subheading and sub text within ```items.push({
      "name": "An Entry has been added to the Sales Log",
      "value": "Lead Mech: "+ colB +"\nAmount: " + colAB + "\nMats Used: "+ colAN,
      "inline": false```

**Comment by SgtGino** [comment] 2022-09-20 12:32
HOLD THE PHONE I THINK I'VE DONE IT 2 SECS

**Comment by Kelo** [comment] 2022-09-20 12:41
so the issue we're encountering is because the event passed by change type doesn't have a range attribute.
So `e.range` won't work with onChange. 
I'm trying to find a way of getting it.

**Comment by SgtGino** [comment] 2022-09-20 12:42
**CURRENT CODE**

var POST_URL = "MY DISCORD WEBHOOK"

var randomColor = Math.floor(Math.random()*16777215);

function onChange(e){

if (e.changeType == "OTHER") { 

var items = [];

  var sheet_name = e.range.getSheet().getName();
  var rangeNotation = e.range.getA1Notation();
  var oldValue = e.oldValue;
  var value = e.value;
  var rangeNotation = e.range.getA1Notation();
  var rowNumber =  rangeNotation.substring(1,2);

var colB = e.range.getSheet().getRange("B"+rowNumber).getValue();
var colAB = e.range.getSheet().getRange("AB"+rowNumber).getValue();
var colAN = e.range.getSheet().getRange("AN"+rowNumber).getValue();

  // If you only want to watch a certain column
  var column_id = 2
  // If not the column you want to watch
  if (column_id < e.range.getColumn() || column_id > e.range.getLastColumn() ){
      // Do nothing
      return;
  }

  if (value == undefined && oldValue == undefined){
    if (rangeNotation.includes(':')){
      reason = "Multiple Cells edited";
    }
    else{
      reason = "Cell value deleted";
    }
  }
  else{
    if (oldValue == undefined){
      oldValue = "Empty cell";
    }

    if (value == undefined){
        value = "Empty cell";
    }
    reason = oldValue + " -> " + value
  }
  
}



 var items = [];

var rangeNotation = e.range.getA1Notation();
  var rowNumber =  rangeNotation.substring(1,2);

var colB = e.range.getSheet().getRange("B"+rowNumber).getValue();
var colAB = e.range.getSheet().getRange("AB"+rowNumber).getValue();
var colAN = e.range.getSheet().getRange("AN"+rowNumber).getValue();

    items.push({
      "name": "An Entry has been added to the Sales Log",
      "value": "Lead Mech: "+ colB +"\nAmount: " + colAB + "\nMats Used: "+ colAN,
      "inline": false
  });

  var options = {
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
        },
        "payload": JSON.stringify({
            "content": "‌",
            "embeds": [{
                "title": "JOB COMPLETE",
                "color": randomColor,
                "fields": items,
                "timestamp": new Date().toISOString()
            }]
        })
    };

    UrlFetchApp.fetch(POST_URL, options);

**Comment by SgtGino** [comment] 2022-09-20 12:42
> 

Ahh ok understood. THANK YOU SO MUCH! buggin the lfe outta me!

**Comment by Kelo** [comment] 2022-09-20 12:44
Could you put this at the top of the function and show me what the log shows?
`Logger.log(JSON.stringify(e)); `

**Comment by SgtGino** [comment] 2022-09-20 12:46
![image](https://user-images.githubusercontent.com/109251153/191261346-17ecd7b0-83a4-46e1-aacd-c43ee90dbc07.png)

That what you need Kelo?

**Comment by Kelo** [comment] 2022-09-20 12:48
Misclicked.

You've leaked your webhook url btw. Might wanna change that.

Put the logger line below `function onChange(e)`

**Comment by SgtGino** [comment] 2022-09-20 12:48
Oops yeah my bad! removed now :)

**Comment by SgtGino** [comment] 2022-09-20 12:50
![image](https://user-images.githubusercontent.com/109251153/191262185-1ab93003-cdff-4d79-a632-3a519f7c7fa5.png)

**Comment by Kelo** [comment] 2022-09-20 12:51
Did you trigger it via jotform? Hitting RUN won't test it properly, you need to check the execution log in triggers.

**Comment by Commitosaurus** [comment] 2022-09-20 12:52
Double my bad.. 2 secs :)

**Comment by SgtGino** [comment] 2022-09-20 12:54
![image](https://user-images.githubusercontent.com/109251153/191263186-93bb8a0f-6ef0-49ef-bf1a-f85f4c969aeb.png)

**Comment by Kelo** [comment] 2022-09-20 12:57
We can't get the range :( meaning we can't get the row number.
We could get the last row with data if that works

**Comment by SgtGino** [comment] 2022-09-20 12:58
Yeah that would work perfect!

**Comment by SgtGino** [comment] 2022-09-20 13:00
Would be the values of colB, colAB & colAN on the last row everytime its updated won't it so if we can get that and put it into

colB +"\nAmount: " + colAB + "\nMats Used: "+ colAN then that would do the trick!!

**Comment by Kelo** [comment] 2022-09-20 13:01
What's the name of the sheet with the data? Should be on the tabs at the bottom

**Comment by SgtGino** [comment] 2022-09-20 13:01
Sales

**Comment by Kelo** [comment] 2022-09-20 13:04
Give this a whirl:

```
var POST_URL = "MY DISCORD WEBHOOK"

var randomColor = Math.floor(Math.random()*16777215);

function onChange(e) {

    var items = [];

    if (e.changeType == "OTHER") {

        var sheet = SpreadsheetApp.getActive().getSheetByName('Sales');
        var lastRow = sheet.getLastRow();
        var colB = sheet.getRange("B" + lastRow).getValue();
        var colAB = sheet.getRange("AB" + lastRow).getValue();
        var colAN = sheet.getRange("AN" + lastRow).getValue();

        items.push({
            "name": "An Entry has been added to the Sales Log",
            "value": "Lead Mech: " + colB + "\nAmount: " + colAB + "\nMats Used: " + colAN,
            "inline": false
        });
    } else{
        return;
    }
    
    var options = {
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
        },
        "payload": JSON.stringify({
            "content": "‌",
            "embeds": [{
                "title": "JOB COMPLETE",
                "color": randomColor,
                "fields": items,
                "timestamp": new Date().toISOString()
            }]
        })
    };

    UrlFetchApp.fetch(POST_URL, options);
}
```

**Comment by Commitosaurus** [comment] 2022-09-20 13:15
NOT ALL HERO'S WEAR CAPES! XD

THANK you so sooo much for your persistance with me on this Kelo, it's working!!! :)

The script above didn't intially work so I grabbed the;

```
var sheet = SpreadsheetApp.getActive().getSheetByName('Sales');
        var lastRow = sheet.getLastRow();
        var colB = sheet.getRange("B" + lastRow).getValue();
        var colAB = sheet.getRange("AB" + lastRow).getValue();
        var colAN = sheet.getRange("AN" + lastRow).getValue();
```

and put that with the added ```var items = [];``` I put in when getting the sub heading working and hey presto.... works like a charm. I reckon there is some lines I can get rid of but I'm just super impressed we've got it working thank you thank you thank you. will send the end script over in a sec!

**Comment by Kelo** [comment] 2022-09-20 13:18
Np :)

**Comment by Commitosaurus** [comment] 2022-09-20 13:18
```
var POST_URL = "MY DISCORD WEBHOOK URL"

var randomColor = Math.floor(Math.random()*16777215);

function onChange(e){

Logger.log(JSON.stringify(e));

if (e.changeType == "OTHER") {}

var items = [];

        var sheet = SpreadsheetApp.getActive().getSheetByName('Sales');
        var lastRow = sheet.getLastRow();
        var colB = sheet.getRange("B" + lastRow).getValue();
        var colAB = sheet.getRange("AB" + lastRow).getValue();
        var colAN = sheet.getRange("AN" + lastRow).getValue();

    items.push({
      "name": "An entry has been added to the Sales Log",
      "value": "Lead Mech: "+ colB +"\nAmount: " + colAB + "\nMats Used: "+ colAN,
      "inline": false
  });

  var options = {
        "method": "post",
        "headers": {
            "Content-Type": "application/json",
        },
        "payload": JSON.stringify({
            "content": "",
            "embeds": [{
                "title": "JOB COMPLETE",
                "color": randomColor,
                "fields": items,
                "timestamp": new Date().toISOString()
            }]
        })
    };

    UrlFetchApp.fetch(POST_URL, options);
}
```

**Closed as completed** 2022-09-20 13:20 UTC

**Comment by Commitosaurus** [comment] 2024-02-04 09:33
Hey @Kelo, hope you're well? I haven't used this script for some time but have a need for it once more. It fired back up mostly as expected on a new webhook URL however I seem to be getting duplicate embeds being posted on Discord. I recollect it did this before but only when used for the first time in the day intermittlently.

Any ideas as I'm unsure of whether its a loop or a lag in the API > Discord hook that could cause duplicate embeds being posted.

As always, any support on this would be greatly appreacited :)
