### ISSUE TITLE
Possible to limit triggers?

### ISSUE THREAD

**Issue by internet-tubes** [Kelo/Google-Sheets-to-Discord#9] opened 2023-09-17 20:50 UTC
This script works great, but is it possible to limit the triggers within a timeframe?

In my case, I want a maximum of one trigger every 24 hours. So if any cell in the sheet is edited, it will post to Discord, but there will be a 24 hour cooldown before the next post.

I essentially want a notification saying the sheet was updated, but I'm not looking to spam messages if numerous edits are made.

**Comment by internet-tubes** [comment] 2023-09-17 21:56
For anyone else looking for this, I believe I got it working using the Properties service:
```js
var editCooldownKey            = 'onEditCooldown';
var editCooldownInMilliseconds = 86400 * 1000;
var currentTimestamp           = new Date().getTime();
var scriptProperties           = PropertiesService.getScriptProperties();
var lastEditTimestamp          = scriptProperties.getProperty( editCooldownKey );

// If not set or have passed the cooldown, reset the cooldown. Otherwise, do not proceed
if ( lastEditTimestamp === null || currentTimestamp - lastEditTimestamp > editCooldownInMilliseconds ) {
    scriptProperties.setProperty( editCooldownKey, currentTimestamp );
} else {
    return;
}
```

**Comment by Kelo** [comment] 2023-09-18 07:54
Good to see you got it working 😄 

I'll close this for now, feel free to reopen if it's not working as intended.

**Closed as completed by Kelo** 2023-09-18 07:54 UTC
